### **Weighted sum in PyTorch using Linear Algebra**

$$
z = b + \sum^{m}_{j = 1}x_{j}w_{j} \\[10pt]
z = b + \textbf{x}\textbf{w}
$$
which is basically dot product of $\textbf{x}$ and $\textbf{w}$
$$
\textbf{x} = \begin{bmatrix} x_{1} \\ x_{2} \\ . \\ . \\ . \\ x_{m} \end{bmatrix} \space \textbf{w} = \begin{bmatrix} w_{1} \\ w_{2} \\ . \\ . \\ . \\ w_{m} \end{bmatrix}
$$

In [1]:
import torch

In [2]:
b = torch.tensor([0.])
w = torch.tensor([1.2, 2.2])
x = torch.tensor([3.3, 4.3])

x.dot(w) + b

tensor([13.4200])

### **A small benchmark**

In [3]:
def no_pytorch(x, w, b):
  output = b
  for x_, w_ in zip(x, w):
    output += x_ * w_
  
  return output

In [4]:
import random
random.seed(123)

In [5]:
b = 0.
w = [random.random() for _ in range(1_000)]
x = [random.random() for _ in range(1_000)]

In [6]:
%timeit no_pytorch(x, w, b)

55.9 µs ± 14.3 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [7]:
def with_pytorch(x, w, b):
  return x.dot(w) + b

In [8]:
b = torch.tensor(b)
w = torch.tensor(w)
x = torch.tensor(x)

In [9]:
%timeit with_pytorch(x, w, b)

3.71 µs ± 395 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### **One more benchmark, but for matrix**

In [14]:
b = 0.
X = [[random.random() for _ in range(1_000)]
      for i in range(500)]
w = [random.random() for _ in range(1_000)]

In [15]:
def no_pytorch_mat(X, w, b):
  outputs = []
  for x in X:
    output = b
    for x_, w_ in zip(x, w):
      output += x_ * w_
    outputs.append(output)

  outputs

In [16]:
%timeit no_pytorch_mat(X, w, b)

23.6 ms ± 2.67 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [17]:
b = torch.tensor(b)
w = torch.tensor(w)
X = torch.tensor(X)

In [18]:
def with_pytorch_mat(X, w, b):
  return X.matmul(w) + b

In [19]:
%timeit with_pytorch_mat(X, w, b)

50.1 µs ± 5.19 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### **Multiplying $2$ randomly generated matrices**

In [21]:
X = torch.rand(100, 10)
W = torch.rand(50, 10)

R = torch.matmul(X, W.T)
R.shape

torch.Size([100, 50])

### **Broadcasting**

In [22]:
a = torch.tensor([1.1, 2.1, 3.1, 4.1])
b = torch.tensor([5.6])

a + b

tensor([6.7000, 7.7000, 8.7000, 9.7000])

In [23]:
A = torch.tensor([
  [1.1, 2.1, 3.1, 4.1],
  [1.2, 2.2, 3.2, 4.2]
])
B = torch.tensor([5.4, 5.5, 5.6, 5.7])

A + B

tensor([[6.5000, 7.6000, 8.7000, 9.8000],
        [6.6000, 7.7000, 8.8000, 9.9000]])