In [1]:
import torch

### **A very generic model definition**

In [ ]:
class DummyClassifier(torch.nn.Module):
  def __init__(self):
    # Define the model params here
  
  def forward(self, x):
    outputs = None
    # Define how the model produces output
    # i.e. outputs = some computation

    return outputs

**Train the model**

In [ ]:
model = DummyClassifier()
optimizer = torch.optim.SGD(...)

for epoch in range(epochs):
  for x, y in train_dataloader:
    # Forward propagation
    outputs = model(x)
    loss = loss_fn(outputs, y)

    # Backward propagation
    optimizer.zero_grad() # To stop the gradients from accumulating
    loss.backward()

    # Update model params
    optimizer.step()

### **Using pre-made neural networks from PyTorch**

**Weighted sum**
$$
z = \textbf{w}\textbf{x} + b
$$
is already implemented in PyTorch as `torch.nn.Linear`

In [3]:
torch.manual_seed(200)

In [4]:
linear = torch.nn.Linear(
  in_features = 2,  # Inputs
  out_features = 1  # Outputs
)

In [7]:
linear.weight

Parameter containing:
tensor([[0.1327, 0.0011]], requires_grad=True)

In [8]:
linear.bias

Parameter containing:
tensor([0.7016], requires_grad=True)

In [9]:
# Single training example
x = torch.tensor([1.2, 0.5])

In [10]:
w = linear.weight.detach()
b = linear.bias.detach()

z = x.matmul(w.T) + b
z

tensor([0.8615])

**Minibatch example**

In [11]:
x = torch.tensor([
  [1.2, 0.5],
  [0.7, 0.8],
  [0.1, 0.2]
])

In [12]:
z = x.matmul(w.T) + b
z

tensor([[0.8615],
        [0.7954],
        [0.7151]])