In [6]:
import torch

### **What is a tensor?**
It's a generalization of vectors, matrices, etc. Can also be considered as data container.

### **What is a scalar?**
It's a rank-0 tensor.

In [5]:
# Python
a = 1.
print(a)

1.0


In [8]:
# PyTorch
a = torch.tensor(1.)
print(a)
print(a.shape)

tensor(1.)
torch.Size([])


### **What is a vector?**
It's a rank-1 tensor

In [9]:
# Python
a = [1., 2., 3.]
print(a)

[1.0, 2.0, 3.0]


In [10]:
# PyTorch
a = torch.tensor([1., 2., 3.])
print(a)
print(a.shape)

tensor([1., 2., 3.])
torch.Size([3])


### **What is a matrix?**
It's a rank-2 tensor

In [14]:
a = torch.tensor([
  [1., 2., 3.],
  [2., 3., 4.]
])

print(a.shape)
print(a.ndim)
print(a.dtype)

torch.Size([2, 3])
2
torch.float32


### **3D Tensor**
An RGB image. It is a stack of matrices

In [12]:
a = torch.tensor([
  [
    [1., 2., 3.],
    [2., 3., 4.]
  ],
  [
    [5., 6., 7.],
    [8., 9., 10.]
  ]
])
print(a.shape)

torch.Size([2, 2, 3])


### **4D Tensor**
Rank-4 tensor. A stack of coloured images

[`We can think of PyTorch tensors as NumPy arrays with some additional functionality, such as automatic differentiation and computations on a GPU.`]()

### **Creating tensor from NumPy array**

In [15]:
import numpy as np

In [17]:
np_array = np.array([1., 2., 3.])
a = torch.from_numpy(np_array)
print(a)
# OR
a = torch.tensor(np_array)
print(a)

tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float64)


**Change datatype**

In [18]:
print(a.dtype)
a = a.to(torch.float32)
print(a.dtype)

torch.float64
torch.float32


**Check device**

In [21]:
a.device

device(type='cpu')

**Change the shape of tensor**

In [25]:
a = torch.tensor([
  [1., 2., 3.],
  [2., 3., 4.]
])
print(a)

tensor([[1., 2., 3.],
        [2., 3., 4.]])


In [26]:
print(a.view(3, 2))

tensor([[1., 2.],
        [3., 2.],
        [3., 4.]])


**Transpose of a tensor**

In [27]:
print(a.T)

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])
